### ISSUE TITLE
disport and withdrawls

### ISSUE THREAD

**Issue by npomfret** [coinfloor/API#11]
the https://github.com/coinfloor/API/blob/master/BIST.md#user-transactions endpoint requires a currency pair.  What do I specify if i just want to get a list of my deposits and withdrawals?

**Comment by whitslack** [comment]
BIST, which emulates Bitstamp's v1 API, is not multicurrency. At present there is no programmatic way to list deposits and withdrawals in _all_ supported currencies in one call. You can, however, retrieve by email a CSV listing of all deposits and withdrawals on the "Deposits and Withdrawals History" page in the the "My Account" section of the web site.

**Comment by npomfret** [comment]
Thanks.  This is crazy important, any idea how to get coin floor to add it?

**Comment by whitslack** [comment]
I'm asking them, but I think this is going to be a low priority since you already can retrieve all your deposits and withdrawals programmatically by requesting them for each asset pair and merging the results on your end.

**Comment by npomfret** [comment]
Ok, so just request transactions for every currency pair and de-dup by using the transaction id?

If you are in touch with them, it would be really useful to be able to get the destination address and network transaction id as well.
