### ISSUE TITLE
HTTP public ticker CORS issue

### ISSUE THREAD

**Issue by lukeliasi** [coinfloor/API#16]
I am trying to call: https://webapi.coinfloor.co.uk:8090/bist/XBT/GBP/ticker/ using JavaScript but get a cors issue:

> Failed to load https://webapi.coinfloor.co.uk:8090/bist/XBT/GBP/ticker/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

```
fetch('https://webapi.coinfloor.co.uk:8090/bist/XBT/GBP/ticker/').then(response => { 
  return response.json();
}).then((data) => {
  console.log(data);
}).catch((err) => {
  console.log(err)
});
```

**Comment by whitslack** [comment]
The BIST API isn't really intended to be called from a web browser. BIST is an emulation layer provided as stopgap measure to help trading software written for the Bitstamp API to transition easily to Coinfloor. For new applications, please use Coinfloor's [WebSocket API](https://github.com/coinfloor/API/blob/master/WEBSOCKET-README.md). The BIST emulation is implemented atop the WebSocket API, meaning you will get better performance by using the WebSocket API directly, and you will not be polling, so server load is lessened as well.

```
Coinfloor.on("TickerChanged", function (ticker) {
  console.log(ticker);
});
Coinfloor.connect(null, function () {
  this.watchTicker(0xF800, 0xFA20, true, function (reply) {
    console.log(reply);
  });
});
```

**Comment by lukeliasi** [comment]
Ok that makes sense. The livestream of data from websockets will be useful, I will look into that -
 thanks!
