### ISSUE TITLE
date header

### ISSUE THREAD

**Issue by npomfret** [coinfloor/API#22]
https://github.com/coinfloor/API/blob/master/BIST.md#order-book

What does the text:

> Please refer to the Date HTTP response header for any date or time information you may require.

mean in relation to getting gan order book?

**Comment by whitslack** [comment]
It makes more sense if you refer to the [`BIST-Migration.md`](https://github.com/coinfloor/API/blob/master/BIST-Migration.md#order-book) document:
>Bitstamp includes an undocumented `timestamp` field in the returned JSON object. Coinfloor does not include this field. Please refer to the `Date` HTTP response header.

**Comment by npomfret** [comment]
Right.  But what does the date header field represent?  When the order book was generated?

**Comment by whitslack** [comment]
It's the time at which the returned snapshot of the order book was captured.

**Comment by npomfret** [comment]
thanks
