### ISSUE TITLE
minimum order sizes

### ISSUE THREAD

**Issue by npomfret** [coinfloor/API#24]
I wanted to place some test orders.  Is there somewhere I can find the minimum order size?

I found this https://coinfloor.zendesk.com/hc/en-us/articles/201721837-What-is-the-minimum-amount-of-bitcoin-that-can-be-traded-.  Is it accurate?  And what about the BCH markets?

**Comment by whitslack** [comment]
The order quantity can't be zero, but any other integer is acceptable (provided you have sufficient account balance). Note that a quantity of `1` in the API means 0.0001 XBT or 0.0001 BCH.

Also note that an order to buy `1` of anything will get closed without trading anything if/when it matches with a sell order, as there isn't enough reserved counter asset there to make a trade **and** pay the fee. I'd recommend testing with a quantity of `2` (or `-2`).

**Comment by npomfret** [comment]
Thanks

**Comment by npomfret** [comment]
@whitslack what currency is the fee paid in?

**Comment by coinfloor-ltd** [comment]
Hi Nick,

All of our fee details are on the following page:
https://www.coinfloor.co.uk/fees If this page doesn't answer your specific
question please let us know so we can clarify further and update the page
if needed.

Kind regards,
Tim.

**Comment by npomfret** [comment]
Um, yes that's why I'm asking the question.  Do you understand what I'm asking?

**Comment by coinfloor-ltd** [comment]
Withdrawls, fees are in the native currency (i.e. withdrawal FIAT, fee is
in FIAT. Withdrawal XBT, fee is in XBT)
Trades, fees are in FIAT

**Comment by npomfret** [comment]
Thanks!

Any chance of getting some answers to the other open questions on here?
