### ISSUE TITLE
Possible flaw in authentication process

### ISSUE THREAD

**Issue by linmaosong2018** [coinfloor/API#26]
Currently, to generate a signature for the websocket:
1. User ID and password are combined.
2. The combination goes through SHA-224 to produce a 224-bit number
3. The 224-bit number is treated as a private key under secp224k1

The problem is not all 224-bit numbers are valid private keys. As per secp224k1, the number needs to be under the order n of G
n = 01 00000000 00000000 00000000 0001DCE8 D2EC6184 CAF0A971 769FB1F7

Therefore, there is a chance (small but not zero) a user being unable to authenticate, due to their ID/password combination's hash falling outside of the valid range.

**Comment by whitslack** [comment]
> not all 224-bit numbers are valid private keys

Incorrect. All 224-bit numbers are strictly less than secp224k1's *n*.

Note that even if *n* were less than 2^224, there still would be no problem with using private keys greater than *n*. It's just that private keys 1 and *n*+1 have the same public key and are thus interchangeable.

**Comment by linmaosong2018** [comment]
Yes you are right! I made a error in calculating the n's bits
