### ISSUE TITLE
BTC Withdrawals

### ISSUE THREAD

**Issue by jevdiego** [coinfloor/API#27]
Good day,

I see in the documentation that you do not support withdrawals. Is this on the roadmap to be developed? And if so, is it possible to get an ETA?

Thanks,
Jevon

**Comment by whitslack** [comment]
You are able to submit a withdrawal request using the [BIST API](https://github.com/coinfloor/API/blob/master/BIST-Migration.md), which is an emulation of Bitstamp's v1 API. Note the differences from Bitstamp's implementation: the `address` parameter is disallowed, and no withdrawal identifier is returned.

**Comment by kevinb1989** [comment]
Hi guys,

It's good to know that this is still working. So what endpoint should I send to POST request to?

https://webapi.coinfloor.co.uk/bist/<base>/<counter>/bitcoin_withdrawal
OR https://webapi.coinfloor.co.uk/bist/bitcoin_withdrawal
OR https://webapi.coinfloor.co.uk/bitcoin_withdrawal
