### ISSUE TITLE
trades between dates

### ISSUE THREAD

**Issue by dlefcoe** [coinfloor/API#45]
Is there a method in the `coinfloor.py` module (in Python) that allows the user to get all trades between a start and end date for a given currency ? or instruction on how to do this please ?

thanks.

**Comment by kamilbolka** [comment]
No there isn't. However, you can use our BIST v2 [User Transactions](https://github.com/coinfloor/API/blob/master/BIST_v2.md#user-transactions) endpoint to retrieve all trades, deposits and withdrawals for the given currency.

**Comment by dlefcoe** [comment]
Thanks for the reply.

When i replace the url to the url endpoint given, it fails, so was wondering the following:

Is this endpoint usable via the websocket or does the user need to acces with requests?
(or, **even better**, if there is a basic example this would be most helpful).

**Comment by dlefcoe** [comment]
solution is like this:

`    url = 'https://webapi.coinfloor.co.uk/v2/bist/XBT/GBP/user_transactions/'
    
    data = {'key':'value'}
    r = requests.post(url, data=data, auth=('username', 'password') )
    print(r.status_code)
    print(r.text)
`


need to have the data variable otherwise get `status_code` = 415 error.
