### ISSUE TITLE
limits docs

### ISSUE THREAD

**Issue by npomfret** [coinfloor/API#9]
The limits [docs](https://github.com/coinfloor/API/blob/master/LIMITS.md) have the following for open orders queries:

`Open orders | 1,000 per user`

1000 per user?  Surely there's a time period missing here?

**Comment by whitslack** [comment]
This limit is not a rate over time. This is the maximum number of open orders that a user may have concurrently. This limit is in place to prevent users from overloading the order books with huge numbers of small orders.

**Comment by npomfret** [comment]
Thanks!
